import {Github,Linkedin,Mail,MapPin,Download,ExternalLink,Cloud,Container,Code2,ShieldCheck,Activity,Database,Workflow,BrainCircuit,Award,BriefcaseBusiness} from 'lucide-react'
const skills=[
{icon:Cloud,title:'Cloud',items:'Microsoft Azure, AWS, Azure Functions, AKS, ECS, Lambda, SQS'},
{icon:Container,title:'Containers',items:'Docker, Kubernetes, AKS, EKS, Helm'},
{icon:Workflow,title:'DevOps & IaC',items:'Terraform, GitHub Actions, Azure DevOps, CI/CD, Bicep'},
{icon:Code2,title:'Development',items:'Python, Golang, SQL, REST APIs, Microservices, PowerShell'},
{icon:Activity,title:'Observability',items:'Azure Monitor, Application Insights, Grafana, Loki, CloudWatch'},
{icon:ShieldCheck,title:'Security',items:'Azure Key Vault, RBAC, Entra ID, IAM, secure secrets management'},
{icon:Database,title:'Data',items:'PostgreSQL, InfluxDB, Redis, Azure Storage, time-series pipelines'},
{icon:BrainCircuit,title:'AI',items:'Azure OpenAI, anomaly explanations, AI-powered cloud workflows'}]
const bullets=['Built an end-to-end cloud-native platform that detects abnormal stock-price movements using Python and Azure Functions.','Implemented event-driven processing with Azure Event Hubs and secure storage with Azure Storage.','Provisioned repeatable infrastructure using Terraform and protected secrets with Azure Key Vault and RBAC.','Containerized services using Docker and deployed workloads to Azure Kubernetes Service with Helm.','Automated infrastructure and application delivery through GitHub Actions CI/CD pipelines.','Integrated Azure OpenAI to produce clear, AI-generated explanations for detected anomalies.','Created observability dashboards using Azure Managed Grafana, Azure Monitor, Application Insights and Loki.']
export default function App(){return <div><nav className="nav"><a className="brand" href="#home">SK</a><div className="navLinks"><a href="#about">About</a><a href="#skills">Skills</a><a href="#project">Project</a><a href="#experience">Experience</a><a href="#contact">Contact</a></div></nav><main>
<section id="home" className="hero section"><div className="heroText"><p className="eyebrow">CLOUD • DEVOPS • SOFTWARE ENGINEERING</p><h1>Sandeep Kaur</h1><h2>Building secure, automated and observable cloud platforms.</h2><p className="lead">Software Engineer with 3+ years of experience in Python, Golang, Azure, AWS, Terraform, Docker, Kubernetes, CI/CD and cloud-native architecture.</p><div className="actions"><a className="button primary" href="#project">View Featured Project</a><a className="button secondary" href="./Sandeep_Kaur_Resume.docx" download><Download size={18}/> Download Resume</a></div><div className="socials"><a href="https://github.com/sandeepdevopsinfo-creator" target="_blank"><Github size={20}/> GitHub</a><a href="https://www.linkedin.com/in/sandeep-k-400b30230" target="_blank"><Linkedin size={20}/> LinkedIn</a><a href="mailto:Sandeep.devopsinfo@gmail.com"><Mail size={20}/> Email</a></div></div><div className="heroCard"><div className="terminalDots"><span></span><span></span><span></span></div><pre>{`$ whoami\nSandeep Kaur\n\n$ role\nCloud & DevOps Engineer\n\n$ focus\nAzure | AWS | Kubernetes\nTerraform | Python | CI/CD\n\n$ status\nOpen to opportunities`}</pre></div></section>
<section id="about" className="section"><div className="sectionHeading"><span>01</span><h2>About Me</h2></div><div className="aboutGrid"><div><p>I design and support backend systems, automated cloud infrastructure and Kubernetes-based applications. My work combines software engineering, infrastructure as code, security and production observability.</p><p>I enjoy converting manual processes into reliable automation and building platforms that are scalable, secure and easy to monitor.</p></div><div className="quickFacts"><div><MapPin size={20}/><span>United States</span></div><div><BriefcaseBusiness size={20}/><span>3+ years of experience</span></div><div><Award size={20}/><span>AZ-104 and AZ-900 certified</span></div></div></div></section>
<section id="skills" className="section"><div className="sectionHeading"><span>02</span><h2>Technical Skills</h2></div><div className="skillGrid">{skills.map(({icon:Icon,title,items})=><article className="skillCard" key={title}><Icon size={25}/><h3>{title}</h3><p>{items}</p></article>)}</div></section>
<section id="project" className="section"><div className="sectionHeading"><span>03</span><h2>Featured Project</h2></div><article className="projectCard"><div className="projectTop"><div><p className="eyebrow">AZURE • AI • DEVOPS</p><h3>Azure Stock Anomaly Detection Platform</h3><p>A portfolio-ready event-driven platform for stock-data ingestion, anomaly detection, AI explanations, secure deployment and real-time monitoring.</p></div><BrainCircuit size={54}/></div><ul>{bullets.map(x=><li key={x}>{x}</li>)}</ul><div className="tags">{['Azure Functions','Event Hubs','Terraform','Docker','AKS','Helm','GitHub Actions','Key Vault','Grafana','Azure OpenAI','Python'].map(x=><span key={x}>{x}</span>)}</div><a className="projectLink" href="https://github.com/sandeepdevopsinfo-creator/ai-stock-anomaly-detection-azure" target="_blank">View GitHub Repository <ExternalLink size={17}/></a></article></section>
<section id="experience" className="section"><div className="sectionHeading"><span>04</span><h2>Experience</h2></div><div className="timeline"><article><div className="time">Jan 2025 — Present</div><div><h3>Software Engineer</h3><h4>Idaho Power Company</h4><p>Building Python services, time-series data pipelines, REST APIs, cloud integrations, CI/CD automation and monitoring for utility platforms.</p></div></article><article><div className="time">Jun 2022 — Feb 2024</div><div><h3>Azure DevOps Engineer</h3><h4>Cast AI</h4><p>Developed cloud automation, Python and Golang services, Terraform infrastructure, Kubernetes deployments, observability and CI/CD pipelines.</p></div></article></div></section>
<section className="section"><div className="sectionHeading"><span>05</span><h2>Education & Certifications</h2></div><div className="twoCol"><article className="infoCard"><h3>Master of Science in Information Technology</h3><p>Washington University of Science and Technology</p><p>March 2026</p></article><article className="infoCard"><h3>Microsoft Certifications</h3><p>Azure Administrator Associate — AZ-104</p><p>Azure Fundamentals — AZ-900</p></article></div></section>
<section id="contact" className="section contact"><p className="eyebrow">LET'S CONNECT</p><h2>Interested in working together?</h2><p>I am open to Cloud, DevOps, Platform and Software Engineering opportunities.</p><a className="button primary" href="mailto:Sandeep.devopsinfo@gmail.com"><Mail size={18}/> Email Sandeep</a></section></main><footer><p>© 2026 Sandeep Kaur. Built with React and Vite.</p></footer></div>}
